import Route from '@ember/routing/route';

export default class ApplicationRoute extends Route {
  model() {
    return [
      {
        idx: '587',
        name: 'Amersfoort',
        street: 'De Windturbine',
        streetnr: '1',
        zip: '3815',
        city: 'Amersfoort',
        image: null,
        latitude: '52.163627',
        longitude: '5.424038',
        operatorname: 'Fountain Fuel',
        operatorlogo: null,
        hostname: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'PLANNED',
        combinedremark:
          'The opening of our first station is set to land in early May 2023. The cevil works are in full swing!',
        status_unknown: false,
        progress_percent: '23',
        progress_description: 'At the planning stage',
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_large: 't',
        has_350_small: 't',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        news: 'The opening of our first station is set to land in early May 2023. The cevil works are in full swing!',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '523',
        name: 'Amsterdam - Australiëhavenweg',
        street: 'Australiëhavenweg',
        streetnr: '116',
        zip: '1046 BR',
        city: 'Amsterdam',
        image: '3852',
        latitude: '52.399877',
        longitude: '4.795298',
        operatorname: 'Orange Gas',
        operatorlogo: null,
        hostname: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'PLANNED',
        combinedremark: null,
        status_unknown: false,
        progress_percent: '82',
        progress_description: 'Preparing for commissioning',
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_large: 'f',
        has_350_small: 'f',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [],
      },
      {
        idx: '479',
        name: 'Arnhem',
        street: 'Westervoortsedijk  ',
        streetnr: '71C',
        zip: '6827 AV',
        city: 'Arnhem',
        image: '2337',
        latitude: '51.970573',
        longitude: '5.946628',
        operatorname: 'PitPoint clean fuels B.V.',
        operatorlogo: null,
        hostname: null,
        operatorhotline: '+31 30 410 08 88',
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'OPEN',
        combinedremark: null,
        status_unknown: false,
        progress_percent: null,
        progress_description: null,
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: 'EUR 18.50 / kg',
        has_700_small: 't',
        has_350_small: 't',
        has_350_large: 't',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymentinfo: 'Debit and credit cards',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
          {
            name: 'multitank',
            apiname: 'MULTITANK',
            descr: 'MultiTankcard',
            page: null,
            directurl: null,
          },
          {
            name: 'total_card',
            apiname: 'TOTAL',
            descr: 'TOTAL fuel card',
            page: null,
            directurl: null,
          },
          {
            name: 'travelcard',
            apiname: 'TRAVELCARD',
            descr: 'travelcard',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '413',
        name: 'BP Kerkhof & Zn',
        street: 'Binckhorstlaan',
        streetnr: '100',
        zip: '2516',
        city: 'Den Haag',
        image: '3448',
        latitude: '52.0715768',
        longitude: '4.3353721',
        operatorname: 'BP Kerkhof & Zn',
        operatorlogo: null,
        hostname: null,
        operatorhotline: '+31 70 347 35 04',
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'OPEN',
        combinedremark: null,
        status_unknown: false,
        progress_percent: null,
        progress_description: null,
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: '',
        price_message: 'EUR 16.95 / kg',
        has_700_small: 't',
        has_350_small: 't',
        has_350_large: 't',
        opening_hours: 'Mon–Sun: 05:00–24:00',
        fundingpage: '',
        paymenttypes: [
          {
            name: 'cash',
            apiname: 'CASH',
            descr: 'Cash',
            page: null,
            directurl: null,
          },
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
          {
            name: 'girocard',
            apiname: 'girocard',
            descr: 'girocard',
            page: null,
            directurl: null,
          },
          {
            name: 'dkv',
            apiname: 'DKV',
            descr: 'DKV fuel card',
            page: null,
            directurl: null,
          },
          {
            name: 'multitank',
            apiname: 'MULTITANK',
            descr: 'MultiTankcard',
            page: null,
            directurl: null,
          },
          {
            name: 'routex',
            apiname: 'ROUTEX',
            descr: 'Routex fuel card',
            page: null,
            directurl: null,
          },
          {
            name: 'travelcard',
            apiname: 'TRAVELCARD',
            descr: 'travelcard',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '565',
        name: 'GP Groot',
        street: 'Diamantweg',
        streetnr: '32',
        zip: '1812 RC',
        city: 'Alkmaar',
        image: null,
        latitude: '52.60207',
        longitude: '4.75282',
        operatorname: null,
        operatorlogo: null,
        hostname: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'PLANNED',
        combinedremark: null,
        status_unknown: false,
        progress_percent: '23',
        progress_description: 'At the planning stage',
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_small: 't',
        has_350_large: 't',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [],
      },
      {
        idx: '465',
        name: 'Green Planet Pesse',
        street: 'Bultinge',
        streetnr: '2',
        zip: '7933TZ',
        city: 'Pesse',
        image: '6458',
        latitude: '52.77393',
        longitude: '6.445174',
        operatorname: 'Green Planet',
        operatorlogo: '1054',
        hostname: null,
        operatorhotline: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'OPEN',
        combinedremark: null,
        status_unknown: false,
        progress_percent: null,
        progress_description: null,
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: 'EUR 19.50 / kg',
        has_700_small: 't',
        has_350_large: 'f',
        has_350_small: 'f',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        comments:
          'High convenience multi fuel station with coffee, snacks, petit restaurant and office space available',
        paymenttypes: [
          {
            name: 'cash',
            apiname: 'CASH',
            descr: 'Cash',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
          {
            name: 'invoice',
            apiname: 'PURCHASE ON INVOICE',
            descr: 'Purchase on invoice',
            page: null,
            directurl: null,
          },
          {
            name: 'multitank',
            apiname: 'MULTITANK',
            descr: 'MultiTankcard',
            page: null,
            directurl: null,
          },
          {
            name: 'travelcard',
            apiname: 'TRAVELCARD',
            descr: 'travelcard',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '561',
        name: 'Greenpoint Oude-Tonge',
        street: 'Tonnisseweg',
        streetnr: '3',
        zip: '3255 LT',
        city: 'Oude-Tonge',
        image: null,
        latitude: '51.70018',
        longitude: '4.20435',
        operatorname: 'Greenpoint',
        operatorlogo: null,
        hostname: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'PLANNED',
        combinedremark: 'Under construction - open in Q3 2023',
        status_unknown: false,
        progress_percent: '43',
        progress_description: 'At the approval stage',
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_small: 't',
        has_350_large: 't',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymentinfo:
          'Van Kessel tankpas, credit cards, debet cards (bankpassen)',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '383',
        name: 'Holthausen Energy Point Groningen',
        street: 'Bornholmstraat',
        streetnr: '41',
        zip: '9723AZ',
        city: 'Groningen',
        image: '4944',
        latitude: '53.209772260757',
        longitude: '6.5956685180944',
        operatorname: 'Holthausen Clean Technology B.V.',
        operatorlogo: null,
        hostname: null,
        operatorhotline: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'OPEN',
        combinedremark:
          'Holthausen Energy Points levert 100% groene waterstof \r\nGemaakt dmv electrolyser en stroom van de zon en de wind.\r\nWaterstof word terplaatse gemaakt.',
        status_unknown: false,
        progress_percent: null,
        progress_description: null,
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: 'EUR 24.95 / kg',
        has_700_small: 't',
        has_350_small: 't',
        has_350_large: 't',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
          {
            name: 'mobile_payment',
            apiname: 'MOBILE_PAYMENT',
            descr: 'Apple Pay, Google Pay',
            page: null,
            directurl: null,
          },
          {
            name: 'multitank',
            apiname: 'MULTITANK',
            descr: 'MultiTankcard',
            page: null,
            directurl: null,
          },
          {
            name: 'travelcard',
            apiname: 'TRAVELCARD',
            descr: 'travelcard',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '517',
        name: 'Hysolar Greenpoint - Nieuwegein',
        street: 'Morsebaan',
        streetnr: '1',
        zip: '3439 NA',
        city: 'Nieuwegein',
        image: '5245',
        latitude: '52.0278386',
        longitude: '5.1048714',
        operatorname: 'Greenpoint',
        operatorlogo: null,
        hostname: null,
        operatorhotline: '+31 (0)55 31 26 093',
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'OPEN',
        combinedremark: null,
        status_unknown: false,
        progress_percent: null,
        progress_description: null,
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_large: 't',
        has_350_small: 'f',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymentinfo: 'Van Kessel tankpas',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
          {
            name: 'multitank',
            apiname: 'MULTITANK',
            descr: 'MultiTankcard',
            page: null,
            directurl: null,
          },
          {
            name: 'travelcard',
            apiname: 'TRAVELCARD',
            descr: 'travelcard',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '545',
        name: 'Kuster Energy Doetinchem',
        street: 'Braamtseweg',
        streetnr: '10',
        zip: '7007 CK',
        city: 'Doetinchem',
        image: null,
        latitude: '51.946',
        longitude: '6.283952',
        operatorname: 'Kuster Energy',
        operatorlogo: '5404',
        hostname: null,
        operatorhotline: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'OPEN',
        combinedremark: null,
        status_unknown: false,
        progress_percent: null,
        progress_description: null,
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_small: 't',
        has_350_large: 't',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
          {
            name: 'dkv',
            apiname: 'DKV',
            descr: 'DKV fuel card',
            page: null,
            directurl: null,
          },
          {
            name: 'uta',
            apiname: 'UTA',
            descr: 'UTA fuel card',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '582',
        name: 'OG Clean Fuels Hoofddorp/Schiphol',
        street: 'Changing Lane',
        streetnr: '10',
        zip: '2132 MD',
        city: 'Hoofddorp',
        image: null,
        latitude: '52.270485',
        longitude: '4.695679',
        operatorname: 'Orange Gas',
        operatorlogo: null,
        hostname: 'DCB Energy',
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'PLANNED',
        combinedremark: null,
        status_unknown: false,
        progress_percent: '62',
        progress_description: 'Completing construction & installation',
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_small: 't',
        has_350_large: 'f',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'dkv',
            apiname: 'DKV',
            descr: 'DKV fuel card',
            page: null,
            directurl: null,
          },
          {
            name: 'multitank',
            apiname: 'MULTITANK',
            descr: 'MultiTankcard',
            page: null,
            directurl: null,
          },
          {
            name: 'travelcard',
            apiname: 'TRAVELCARD',
            descr: 'travelcard',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '369',
        name: 'Rhoon - Rotterdam (Air Liquide)',
        street: 'Groene Kruisweg',
        streetnr: '397',
        zip: '3161 EJ',
        city: 'Rhoon',
        image: '765',
        latitude: '51.86612',
        longitude: '4.43727',
        operatorname: 'Air Liquide NL',
        operatorlogo: '772',
        hostname: null,
        operatorhotline: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'OPEN',
        combinedremark: null,
        status_unknown: false,
        progress_percent: null,
        progress_description: null,
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_small: 't',
        has_350_large: 't',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        comments:
          'Payment with card "Air Liquide Clean energy only". In order to request a fuel card, please contact Koen van Bussel (koen.vanbussel@airliquide.com).\r\n',
        paymenttypes: [
          {
            name: 'alq_card',
            apiname: 'ALQ',
            descr: 'Air Liquide Clean Energy Card',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '551',
        name: 'Roosendaal',
        street: 'Aanwas',
        streetnr: '4',
        zip: '4704 SC',
        city: 'Roosendaal',
        image: null,
        latitude: '51.55825',
        longitude: '4.4536112',
        operatorname: 'PitPoint clean fuels B.V.',
        operatorlogo: null,
        hostname: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'PLANNED',
        combinedremark: null,
        status_unknown: false,
        progress_percent: '82',
        progress_description: 'Preparing for commissioning',
        progress_extratext: null,
        date_commissioning_message: 'April 2023',
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_large: 't',
        has_350_small: 'f',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [],
      },
      {
        idx: '509',
        name: 'Shell Den Ruygen Hoek',
        street: 'A4 , Den Ruygen Hoek-Oost',
        streetnr: null,
        zip: '2132',
        city: 'MA Rijsenhout',
        image: null,
        latitude: '52.25851',
        longitude: '4.685433',
        operatorname: 'Shell Hydrogen',
        operatorlogo: '669',
        hostname: 'Shell',
        operatorhotline: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'OPEN',
        combinedremark:
          'Vandaag, woensdag 15 februari 2023, vinden er kleine onderhoudswerkzaamheden plaats aan het station. Tijdelijke handicaps kunnen voorkomen. // Today, Wednesday, February 15th, 2023, minor maintenance work will take place at the station. Temporary disabilities may occur.',
        status_unknown: false,
        progress_percent: null,
        progress_description: null,
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: 'EUR 17.50 / kg',
        has_700_small: 't',
        has_350_large: 'f',
        has_350_small: 'f',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '540',
        name: 'Shell Westpoort',
        street: 'Galwin',
        streetnr: '6',
        zip: '1043 XX',
        city: 'Amsterdam',
        image: null,
        latitude: '52.396216585178',
        longitude: '4.8006504132389',
        operatorname: 'Shell Hydrogen',
        operatorlogo: '669',
        hostname: null,
        operatorhotline: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'EXCEPTION',
        combinedremark: null,
        status_unknown: false,
        progress_percent: null,
        progress_description: null,
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: 'for more than 24 hours',
        openinghours_nextchange_message: null,
        price_message: 'EUR 17.50 / kg',
        has_700_small: 't',
        has_350_large: 'f',
        has_350_small: 'f',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '452',
        name: 'TotalEnergies Breda',
        street: 'Minervum',
        streetnr: '7000',
        zip: '4817 ZL',
        city: 'Breda',
        image: null,
        latitude: '51.583202',
        longitude: '4.827183',
        operatorname: 'Total Nederland N.V',
        operatorlogo: null,
        hostname: null,
        operatorhotline: '+31 30 410 08 88',
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'OPEN',
        combinedremark: null,
        status_unknown: false,
        progress_percent: '95',
        progress_description: 'Trial operation',
        progress_extratext:
          'Almost done! The station is now in optimisation mode – a standard procedure we carry out at all stations to put the finishing touches on the system. From now on, you can fill up here. You can tell whether the station is actually available or whether final work is being carried out by the small dot on the blue circle: green – the station is available, red – unfortunately out of operation.',
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: 'EUR 18.50 / kg',
        has_700_small: 't',
        has_350_large: 't',
        has_350_small: 'f',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymentinfo:
          'TotalEnergies cars, Meastro, credit cards (Visa & MasterCard), TravelCard, MTc and Berkman card',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
          {
            name: 'multitank',
            apiname: 'MULTITANK',
            descr: 'MultiTankcard',
            page: null,
            directurl: null,
          },
          {
            name: 'total_card',
            apiname: 'TOTAL',
            descr: 'TOTAL fuel card',
            page: null,
            directurl: null,
          },
          {
            name: 'travelcard',
            apiname: 'TRAVELCARD',
            descr: 'travelcard',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '521',
        name: 'TotalEnergies Capelle',
        street: 'Capelseweg',
        streetnr: '399',
        zip: '2908 MD',
        city: 'Capelle aan den IJssel',
        image: null,
        latitude: '51.954017',
        longitude: '4.562925',
        operatorname: 'Total Nederland N.V',
        operatorlogo: null,
        hostname: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'PLANNED',
        combinedremark: null,
        status_unknown: false,
        progress_percent: '82',
        progress_description: 'Preparing for commissioning',
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_large: 't',
        has_350_small: 'f',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [],
      },
      {
        idx: '520',
        name: 'TotalEnergies Utrecht',
        street: 'De Heldinnenlaan',
        streetnr: '4',
        zip: null,
        city: 'Utrecht',
        image: null,
        latitude: '52.116884',
        longitude: '5.03035',
        operatorname: 'Total Nederland N.V',
        operatorlogo: null,
        hostname: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'PLANNED',
        combinedremark: null,
        status_unknown: false,
        progress_percent: '43',
        progress_description: 'At the approval stage',
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_large: 't',
        has_350_small: 'f',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [],
      },
      {
        idx: '557',
        name: 'TotalEnergies Veldhoven',
        street: 'De Run',
        streetnr: '4232',
        zip: '5503 LL',
        city: 'Veldhoven',
        image: null,
        latitude: '51.411687547931',
        longitude: '5.4281576731745',
        operatorname: 'Total Nederland N.V',
        operatorlogo: null,
        hostname: null,
        operatorhotline: '+31 30 410 08 88',
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'EXCEPTION',
        combinedremark: null,
        status_unknown: false,
        progress_percent: '95',
        progress_description: 'Trial operation',
        progress_extratext:
          'Almost done! The station is now in optimisation mode – a standard procedure we carry out at all stations to put the finishing touches on the system. From now on, you can fill up here. You can tell whether the station is actually available or whether final work is being carried out by the small dot on the blue circle: green – the station is available, red – unfortunately out of operation.',
        date_commissioning_message: null,
        activity_message: 'for more than 24 hours',
        openinghours_nextchange_message: null,
        price_message: 'EUR 18.50 / kg',
        has_700_small: 't',
        has_350_small: 't',
        has_350_large: 't',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        news: '700 bar available on appointment.',
        paymenttypes: [
          {
            name: 'creditcard',
            apiname: 'CC',
            descr: 'Credit card',
            page: null,
            directurl: null,
          },
          {
            name: 'debit',
            apiname: 'DEBIT',
            descr: 'Debit card',
            page: null,
            directurl: null,
          },
          {
            name: 'multitank',
            apiname: 'MULTITANK',
            descr: 'MultiTankcard',
            page: null,
            directurl: null,
          },
          {
            name: 'total_card',
            apiname: 'TOTAL',
            descr: 'TOTAL fuel card',
            page: null,
            directurl: null,
          },
          {
            name: 'travelcard',
            apiname: 'TRAVELCARD',
            descr: 'travelcard',
            page: null,
            directurl: null,
          },
        ],
      },
      {
        idx: '566',
        name: 'Van Twist Dordrecht',
        street: 'Laan der Verenigde Naties',
        streetnr: '113',
        zip: '3316 AK',
        city: 'Dordrecht',
        image: null,
        latitude: '51.80427',
        longitude: '4.64618',
        operatorname: null,
        operatorlogo: null,
        hostname: null,
        countryshortname: 'NL',
        funding: null,
        combinedstatus: 'PLANNED',
        combinedremark: null,
        status_unknown: false,
        progress_percent: '23',
        progress_description: 'At the planning stage',
        progress_extratext: null,
        date_commissioning_message: null,
        activity_message: null,
        openinghours_nextchange_message: null,
        price_message: null,
        has_700_small: 't',
        has_350_small: 't',
        has_350_large: 't',
        opening_hours: 'Open 24/7',
        fundingpage: '',
        paymenttypes: [],
      },
    ].map((station) => {
      const price = station.price_message?.match(/\d+.\d+/g)[0] || '-';
      const status = station.combinedstatus
        .split(' ')
        .map((c) => c.charAt(0) + c.toLowerCase().slice(1))
        .join(' ');
      const address =
        station.street + ' ' + station.streetnr + ', ' + station.city;
      const coor = station.latitude + ',' + station.longitude;
      const has_700_small = 't' === station.has_700_small;
      const has_350_large = 't' === station.has_350_large;
      const has_350_small = 't' === station.has_350_small;
      const payments =
        station.paymenttypes.map((type) => type.descr).join(', ') || '-';
      return {
        name: station.name,
        price: price,
        address: address,
        status: status,
        coor: coor,
        has_700_small: has_700_small,
        has_350_large: has_350_large,
        has_350_small: has_350_small,
        payments: payments,
      };
    });
  }
}
